### ISSUE TITLE
`aio discover` bug

### ISSUE THREAD

**Issue by shazron** [adobe/aio-cli#123]
```
aio discover
 ›   Error: Oops:FetchError: invalid json response body at
 ›   https://api.npms.io/v2/search?q=aio-cli-plugin reason: Unexpected token < in JSON at position
 ›   0
```

**Comment by shazron** [comment]
![Screen Shot 2020-03-10 at 1 18 07 PM](https://user-images.githubusercontent.com/36107/76282062-9e323980-62d1-11ea-912c-6df9de529dfe.png)

**Comment by shazron** [comment]
We should use the official search api (might be rate limited) and not npms.io which I believe is sponsored by a lone developer.

**Comment by shazron** [comment]
The service is back up, but we should migrate off it.

**Comment by meryllblanchet** [comment]
Closing as the service is back up.
