### ISSUE TITLE
Provide unit test coverage as html

### ISSUE THREAD

**Issue by tmathern** [adobe/aio-cli#124]
### Expected Behaviour
While developing for AIO, it would be easier for me to be able to see code coverage locally in the browser (HTML format).

### Actual Behaviour
Code coverage data is raw data.

### Reproduce Scenario (including but not limited to)
Run tests in aio-app-scripts or any aio-module and check the content of coverage folder.

#### Steps to Reproduce
Run tests in aio-app-scripts or any aio-module and check the content of coverage folder.

#### Platform and Version
Latest aio (master).

#### Sample Code that illustrates the problem
N/A

#### Logs taken while reproducing problem
N/A

Note: This would be for all aio components.

**Comment by purplecabbage** [comment]
coverage is output in the terminal when you run the tests, is this not sufficient?

**Comment by tmathern** [comment]
I can't see the uncovered lines in the console, especially for lines like:
` const a = this_value || this_other_value `
Only looking at console, I won't see which one is the uncovered one.

**Comment by shazron** [comment]
If a repo has for the jest options `coverageReporters` set, and it does not have the `lcov` value in it, it will not output the html report. Either set it in the array value for the property or omit `coverageReporters` altogether (it is included in the default).

Then launch the `coverage/lcov-report/index.html` file.

**Comment by tmathern** [comment]
@shazron Do I need globally installed dependencies? Because `coverage/lcov-report/index.html` is not created on my machine.

**Comment by tmathern** [comment]
It worked for other aio components, so I think it should also work with aio cli. Therefore closing the question.

**Comment by shazron** [comment]
@tmathern it does not need globally installed dependencies, only jest, which is installed as a dev dependency. 

To be sure, I cloned https://github.com/adobe/aio-cli.git fresh and ran `npm install && npm test`, and checked that there is a `coverage/lcov-report/index.html` file generated.
