### ISSUE TITLE
Question: installing aio cli plugins from a non-adobe scope (any NPM package)

### ISSUE THREAD

**Issue by ahmed-musallam** [adobe/aio-cli#128]
Currently, aio-cli plugins are only installed if they are in the @adobe npm scope.

Will this ever be open to allow anyone to write a plugin push it to NPM registry and install it to aio-cli? Is this on the roadmap at all?

https://github.com/adobe/aio-cli/blob/master/src/commands/discover.js#L98

**Comment by meryllblanchet** [comment]
Hi @ahmed-musallam ,

Thanks for raising this excellent question. We are definitely looking forward to expand the contributions possibilities for our community.

CLI extensibility is one of these topics that we have in mind and an objective we want to work on later this year.

We'd also be totally interested by the use-case you would have in mind.

cc @sarahxxu

**Comment by sarahxxu** [comment]
Any oclif plugin should installable via aio as far as I know, but there is a chance of command collisions, and/or incompatibilities. The code you are pointing to is actually for our “discover” command, which just lists installable plugins from @adobe npm scope.
 
In the future, we are thinking about expanding the discover command by creating another GitHub repo that lists verified community plugins, and contributors could send a pr to add themselves to the list – but this hasn’t been implemented yet.

**Comment by ahmed-musallam** [comment]
Hi Sarah,

I’ll test installing a simple oclif plugin and see if that works. Thanks for the quick turn around!

**Comment by purplecabbage** [comment]
`aio plugins install --help`

installs a plugin into the CLI

USAGE
  $ aio plugins:install PLUGIN...

ARGUMENTS
  PLUGIN  plugin to install

OPTIONS
  -f, --force    yarn install with force flag
  -h, --help     show CLI help
  -v, --verbose

DESCRIPTION
  Can be installed from npm or a git url.

  Installation of a user-installed plugin will override a core plugin.

  e.g. If you have a core plugin that has a 'hello' command, installing a user-installed plugin with a 'hello' 
  command will override the core plugin implementation. This is useful if a user needs to update core plugin 
  functionality in the CLI without the need to patch and update the whole CLI.

ALIASES
  $ aio plugins:add

EXAMPLES
  $ aio plugins:install myplugin 
  $ aio plugins:install https://github.com/someuser/someplugin
  $ aio plugins:install someuser/someplugin

**Comment by ahmed-musallam** [comment]
@purplecabbage perfect! thank you!
