### ISSUE TITLE
--version does not show the version

### ISSUE THREAD

**Issue by kptdobe** [adobe/aio-cli#145]
**Describe the bug**
`version` parameter is always ignored and command gets executed.

**To Reproduce**
Run `aio app --version` -> shows the available options.
Run `aio app run --version` -> executes the run command

**Expected behavior**
The version of the plugin should be displayed.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.06
```
aio --version    
@adobe/aio-cli/3.3.0 darwin-x64 node-v10.18.1
```

**Comment by meryllblanchet** [comment]
Updating the issue thread with a workaround that @kptdobe already knows:

`aio info` will list environmental information from the CLI. This includes the currently installed version of the CLI, but also the list of core and user-installed plugins as well as their version.
