### ISSUE TITLE
[Windows] CMD scripts closes immediately after running

### ISSUE THREAD

**Issue by tmathern** [adobe/aio-cli#169]
### Expected Behaviour
The window should stay open/visible, so we can read what is in there. An example to achieve this is to put `cmd /k` as last command in the script, but there are other solutions.

### Actual Behaviour
Double-click the cmd file in the repo's bin folder, and it will run and close immeditely (using cmd.exe).

### Reproduce Scenario (including but not limited to)
Double-click the cmd file in the repo's bin folder, and it will run and close immeditely (using cmd.exe).

#### Steps to Reproduce
On a Windows machine: Double-click the cmd file in the repo's bin folder, and it will run and close immeditely (using cmd.exe).

#### Platform and Version
Windows 10, Node 14

#### Sample Code that illustrates the problem
N/A

#### Logs taken while reproducing problem
N/A

**Comment by purplecabbage** [comment]
Users are not expected to double-click on .cmd files.  
This is consistent with every other globally installed package in ~/AppData/Roaming/npm

**Comment by tmathern** [comment]
This also happens if you work to extend cli on Windows...

**Comment by tmathern** [comment]
Also, I would recommend to use a `.npmignore` in order to not include it when pushed on npm.

**Comment by tmathern** [comment]
@purplecabbage I mean when you are changing / working on the cli code - which I did for debugging purposes - on Windows, the run.cmd script closes immediately. And I thought this script was made for the purpose of helping cli development?
