### ISSUE TITLE
ERROR_GET_ORGANIZATIONS - reason: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by joseajimenezjr** [adobe/aio-cli#222]
### Expected Behaviour 

Log in no issues

### Actual Behaviour 

Unable to set up environment.

#### Steps to Reproduce

This is in the initial set up. When I run "aio app init" it opens up the Chrome browser and logs me in. Then when I go to my terminal(mac) I get the error "[CoreConsoleAPISDK:ERROR_GET_ORGANIZATIONS] FetchError: request to https://developers.adobe.io/console/organizations failed, reason: self signed certificate in certificate chain". If I look under aio config I have an access token and refresh token.

#### Platform and Version
aio info
```
  System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 26.18 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.7 - /usr/local/bin/npm
  Virtualization:
    Docker: 19.03.8 - /usr/local/bin/docker
  npmGlobalPackages:
    @adobe/aio-cli: 4.0.0
  CLI plugins:
    @adobe/aio-cli 4.0.0 (core)
    @adobe/aio-cli-plugin-app 4.1.0 (core)
    @adobe/aio-cli-plugin-auth 2.4.0 (core)
    @adobe/aio-cli-plugin-certificate 0.2.0 (core)
    @adobe/aio-cli-plugin-config 2.3.0 (core)
    @adobe/aio-cli-plugin-console 3.2.0 (core)
    @adobe/aio-cli-plugin-events 1.1.0 (core)
    @adobe/aio-cli-plugin-info 1.1.1 (core)
    @adobe/aio-cli-plugin-jwt-auth 2.0.4 (user)
    @adobe/aio-cli-plugin-runtime 2.0.0 (core)
    @adobe/aio-cli-plugin-target 1.0.1 (user)
    @oclif/plugin-autocomplete 0.2.0 (core)
    @oclif/plugin-help 2.2.3 (core)
    @oclif/plugin-not-found 1.2.4 (core)
    @oclif/plugin-plugins 1.9.1 (core)
    @oclif/plugin-warn-if-update-available 1.7.0 (core)
```

#### Sample Code that illustrates the problem

aio app init
[CoreConsoleAPISDK:ERROR_GET_ORGANIZATIONS] FetchError: request to https://developers.adobe.io/console/organizations failed, reason: self signed certificate in certificate chain

You are currently in:
1. Org: <no org selected>
2. Project: <no project selected>
3. Workspace: <no workspace selected>

**Comment by meryllblanchet** [comment]
Hi @joseajimenezjr ,

Could I ask you to fill in the required information that are blank in your initial ticket?
Also run `aio info` and provide us the output?

I'm afraid we can't help much otherwise.

Thanks!

**Comment by joseajimenezjr** [comment]
Hi @meryllblanchet 
Where do I get the logs? I  filled out the missing parts to the best  of my ability in the initial issue submission.

Thanks!

**Comment by joseajimenezjr** [comment]
@meryllblanchet I have cleared the configs using aio config:clear as well and reattempted numerous times.

**Comment by meryllblanchet** [comment]
Hi @joseajimenezjr ,

Thanks for the update! Let me loop in our team for a first review and we'll come back very soon with more guidance.

**Comment by shazron** [comment]
There may be a proxy that is installed that may be used for development, like [Charles](https://www.charlesproxy.com/). Are you running Charles or something similar?

Try running `openssl s_client -showcerts -connect developers.adobe.io:443` and see what certs are in your chain.

**Comment by meryllblanchet** [comment]
Hi @joseajimenezjr ,

Did you have the opportunity to try the command suggested by @shazron ? What was the result?

**Comment by joseajimenezjr** [comment]
@meryllblanchet I was able to run the openssl command that @shazron provided and found (3) certs in my chain. 

The first one is from adobe, second and third one is for certadmin@netskope.com

Do you have any idea on how to configure the netskope cert to not throw this error?

Thanks!

**Comment by joseajimenezjr** [comment]
It also says "verify error:num=19:self signed certificate in certificate chain" before printing out the certs and meta data.

**Comment by meryllblanchet** [comment]
Hi @joseajimenezjr , thanks for the confirmation and additional information.
Let's loop in @shazron and @purplecabbage and ask for their feedback.

**Comment by meryllblanchet** [comment]
Also cc @duynguyen as this could be a great candidate for a new section in our [Troubleshooting guide](https://github.com/AdobeDocs/project-firefly/blob/master/getting_started/common_troubleshooting.md).

**Comment by purplecabbage** [comment]
@joseajimenezjr  What do you see when you look at these certs in Keychain Access ?

**Comment by joseajimenezjr** [comment]
@purplecabbage not sure if I can share this information here publicly. Are you speaking of just a screenshot of what I see in the keychain access on my mac?

**Comment by purplecabbage** [comment]
Do you see anything that you can fix, or that requires your attention?

**Comment by shazron** [comment]
Looks like netskope is an IT tool to inspect traffic on the corporate network. https://www.jontsai.com/2018/10/23/kill-netskope-client-on-mac (Don't run that command to kill netskope, however since it might violate your network policy).

Since most likely netskope is required in your network, the other workaround is to disable the self-signed certificate check in node: https://stackoverflow.com/a/52479399

Try (untested) to see if it works:
`NODE_TLS_REJECT_UNAUTHORIZED=0 aio app init`

The command above shouldn't be the final solution however since it renders everything insecure and should only be used as a test.

Your corporate system configuration is outside the scope of this issue. You should contact your IT department to see if you can get the Netskope cert to be trusted on your system, if it can't be removed.

**Comment by joseajimenezjr** [comment]
@shazron thank you for researching this, this was my assumption as well. I am investigating with IT how we can get the netskope cert trusted. The command you provided did work but isnt a safe long term solution.

Thank you!

**Comment by meryllblanchet** [comment]
Hi @joseajimenezjr , I will close this issue as you are investigating further with your IT department.
We'll be glad to help you further in case you'd face other issues related to our CLI and SDK, or if you'd have any additional question we could help you with!
