### ISSUE TITLE
Automate npm releases with ghactions

### ISSUE THREAD

**Issue by purplecabbage** [adobe/aio-cli#225]
We need to reduce the number of people who have the ability to publish to npm, for several reasons, security, cost, ...
We should have a release branch/tag that we use to trigger the option to publish to npm.
Secrets would be rotated for us in a perfect world.

**Comment by purplecabbage** [comment]
A solution to this should also include the same for all repos: looking at https://github.com/adobe/aio-sdk and dependents

**Comment by purplecabbage** [comment]
A simple implementation is now part of the default adobe-repo.
https://github.com/adobe/starter-repo/blob/master/.github/workflow/npm-publish.yml

**Comment by shazron** [comment]
implemented in the new workflows created by Jesse
