### ISSUE TITLE
Can't install AIO on mac m1

### ISSUE THREAD

**Issue by pawee-del** [adobe/aio-cli#339]
### Expected Behaviour
Able to install
### Actual Behaviour
Error when installing
### Reproduce Scenario (including but not limited to)
Logs attached

**Comment by pawee-del** [comment]
[2022-02-06T22_44_57_818Z-debug.log](https://github.com/adobe/aio-cli/files/8011374/2022-02-06T22_44_57_818Z-debug.log)
 Logs attached

**Comment by shazron** [comment]
This is not an aio-cli issue, but a node.js issue on M1. To solve the issue, please read this: https://developer.adobe.com/app-builder/docs/getting_started/common_troubleshooting/#nodejs-with-mac-m1-chip
