### ISSUE TITLE
Generators cannot handle node 18

### ISSUE THREAD

**Issue by purplecabbage** [adobe/aio-cli#378]
### Expected Behaviour
npm i -g @adobe/aio-cli # installs with minimal warnings

### Actual Behaviour
$ npm i -g @adobe/aio-cli
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@adobe/aio-lib-templates@2.2.0',
npm WARN EBADENGINE   required: { node: '^14 || ^16' },
npm WARN EBADENGINE   current: { node: 'v18.12.1', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@adobe/aio-lib-console-project-installation@2.2.0',
npm WARN EBADENGINE   required: { node: '^14 || ^16' },
npm WARN EBADENGINE   current: { node: 'v18.12.1', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@adobe/generator-add-action-generic@0.2.7',
npm WARN EBADENGINE   required: { node: '^14 || ^16' },
npm WARN EBADENGINE   current: { node: 'v18.12.1', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@adobe/generator-add-web-assets-exc-raw-html@0.2.2',
npm WARN EBADENGINE   required: { node: '^14 || ^16' },
npm WARN EBADENGINE   current: { node: 'v18.12.1', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@adobe/generator-add-web-assets-exc-react@0.2.3',
npm WARN EBADENGINE   required: { node: '^14 || ^16' },
npm WARN EBADENGINE   current: { node: 'v18.12.1', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@adobe/generator-app-asset-compute@0.2.3',
npm WARN EBADENGINE   required: { node: '^14 || ^16' },
npm WARN EBADENGINE   current: { node: 'v18.12.1', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@adobe/generator-app-excshell@0.2.2',
npm WARN EBADENGINE   required: { node: '^14 || ^16' },
npm WARN EBADENGINE   current: { node: 'v18.12.1', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@adobe/generator-app-common-lib@0.3.0',
npm WARN EBADENGINE   required: { node: '^14 || ^16' },
npm WARN EBADENGINE   current: { node: 'v18.12.1', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@adobe/generator-app-common-lib@0.3.0',
npm WARN EBADENGINE   required: { node: '^14 || ^16' },
npm WARN EBADENGINE   current: { node: 'v18.12.1', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@adobe/generator-app-common-lib@0.3.0',
npm WARN EBADENGINE   required: { node: '^14 || ^16' },
npm WARN EBADENGINE   current: { node: 'v18.12.1', npm: '8.19.2' }
npm WARN EBADENGINE }

#### Platform and Version

windows 10, node 18.12.1, aio-cli@9.1.1

**Comment by shazron** [comment]
Sent PRs:

- https://github.com/adobe/aio-lib-templates/pull/5
- https://github.com/adobe/aio-lib-console-project-installation/pull/17

The rest have been updated and published:

- adobe/generator-add-action-generic
- adobe/generator-add-web-assets-exc-raw-html
- adobe/generator-add-web-assets-exc-react
- adobe/generator-app-asset-compute
- adobe/generator-app-excshell

**Comment by purplecabbage** [comment]
thanks!
