### ISSUE TITLE
Error: Unknown Error From API: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by sanderlenaerts** [adobe/aio-cli#380]
I am trying to deploy an action to io runtime using aio cli, but I am greeted with an error
`Error: Unknown Error From API: self signed certificate in certificate chain`

We are running 
`aio app deploy --action=<action-name>`

Our network policy changes the certificate for security reasons. This results in aio declining the deploy of our actions.

We already tried passing NODE_TLS_REJECT_UNAUTHORIZED=0  and the --insecure flag, but this is not resolving the issue and the error remains. If we look at the aio cli documentation --insecure should work: https://adobedocs.github.io/adobeio-runtime/reference/cli_use.html

Running aio info;

```
System:
    OS: macOS 12.6.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 26.98 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: Not Found
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Virtualization:
    Docker: 20.10.17 - /usr/local/bin/docker
  npmGlobalPackages:
    @adobe/aio-cli: 9.1.1

  Proxies:
    http: (not set)
    https: https://iit2bapi.be.fet.intapp.eu/adobe
  CLI plugins:
    core:
      @adobe/aio-cli 9.1.1
      @adobe/aio-cli-plugin-app 10.0.3
      @adobe/aio-cli-plugin-app-templates 1.5.1
      @adobe/aio-cli-plugin-auth 3.0.1
      @adobe/aio-cli-plugin-certificate 1.0.1
      @adobe/aio-cli-plugin-config 4.0.1
      @adobe/aio-cli-plugin-console 4.0.1
      @adobe/aio-cli-plugin-events 2.0.2
      @adobe/aio-cli-plugin-info 3.0.1
      @adobe/aio-cli-plugin-runtime 6.0.1
      @adobe/aio-cli-plugin-telemetry 1.1.0
      @oclif/plugin-autocomplete 1.3.7
      @oclif/plugin-help 5.1.20
      @oclif/plugin-not-found 2.3.9
      @oclif/plugin-plugins 2.1.8
      @oclif/plugin-warn-if-update-available 2.0.16
    user:
    link:
```

Any way to get around this?

**Comment by shazron** [comment]
Added support for NODE_TLS_REJECT_UNAUTHORIZED=0 https://github.com/adobe/aio-lib-runtime/issues/111
Reinstall the CLI to pick up the changes.
