### ISSUE TITLE
Module and Plugin Versioning Enhancements

### ISSUE THREAD

**Issue by fmeschbe** [adobe/aio-cli#39]
The current release of the AIO CLI is _1.5.0_. When cloning this repository and printing the version, I expect the version number printed to be higher and maybe even indicative of it to be a development version from Git.

As such, I propose to augment the [`RELEASING.md`](RELEASING.md) file such that the process for releasing would be:

1. Increase the version number to the release version
2. Create the Tag (and GitHub Release ?)
3. Increase the version number to the next patch version with tag

In addition we should the [Update your plugins](https://github.com/adobe/aio-cli/blob/master/RELEASING.md#1-update-your-plugins) section clarify what should be done. 

Maybe we should even create a new Versioning document where we discuss

* Plugin Updates
* Versioning Behaviour
* Discuss the current development version, e.g.:
    * odd versions are dev (from repo) and even are release or 
    * append `-SNAPSHOT` to indicate a git version
* Release Versioning

### Expected Behaviour

When printing the version I get a git repo version indicator, for example:

```sh
npm install
bin/run -v
@adobe/aio-cli/1.5.1-SNAPSHOT darwin-x64 node-v10.15.3
```

### Actual Behaviour

```sh
npm install
bin/run -v
@adobe/aio-cli/1.5.0 darwin-x64 node-v10.15.3
```

#### Steps to Reproduce

```sh
npm install
bin/run -v
@adobe/aio-cli/1.5.0 darwin-x64 node-v10.15.3
```

#### Platform and Version

* Platform: darwin-x64 node-v10.15.3
* Git Commit: (a098849a3](https://github.com/adobe/aio-cli/commit/a098849a3076d8acf48522577604b7a0d37e1ef4)

#### Sample Code that illustrates the problem

see above

#### Logs taken while reproducing problem

n/a

**Comment by shazron** [comment]
@fmeschbe see PR #41, let's review there

**Comment by fmeschbe** [comment]
👍 Thanks
