### ISSUE TITLE
Starting a Documentation Discussion

### ISSUE THREAD

**Issue by fmeschbe** [adobe/aio-cli#40]
The current documentation is restricted to the automatically generated [`README.md`](README.md) file and a couple of standard supportive files plus the actual source, of course.

I propose to start an initiative for documentation of the AIO CLI. This documentation should replicate the existing standard information as found in the contribution, releasing etc. documents found in each repository plus information of how the AIO CLI works, listing and documenting the plugins, as well as explaining how to extend AIO CLI for creating new plugins (probably based on the [boiler plate repo](https://github.com/adobe/aio-cli-plugin-boilerplate).

Last but not least we should add something like the following:

> Visit &lt;&lt;doc-site&gt;&gt; for Documentation

to the `package.json#/description` property.

**Comment by meryllblanchet** [comment]
Link to the official documentation: https://github.com/AdobeDocs/project-firefly
