### ISSUE TITLE
new bug report

### ISSUE THREAD

**Issue by Liamhetherington** [adobe/aio-cli#474]
### Expected Behaviour

Looking to have User groups added to the IMS object for AppBuilder Apps in order to avoid needing to call the User Management API

### Actual Behaviour

Currently need to call the UM API in order to gather groups for a given user. The user is required to authenticate so other aspects of their data is included in the IMS object, but not the groups they belong to. 

#### Environment Info
```
  System:
    OS: macOS 11.7.8
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 875.20 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
  Virtualization:
    Docker: 20.10.14 - /usr/local/bin/docker
  npmGlobalPackages:
    @adobe/aio-cli: 9.3.0
```

**Comment by purplecabbage** [comment]
This is in experience shell apis and not really app builder directly.
see https://github.com/AdobeDocs/exc-app/blob/master/docs/modules/user.md
