### ISSUE TITLE
Oauth Server-to-Server auth with Console Org/Project/Workspace select

### ISSUE THREAD

**Issue by martinatime** [adobe/aio-cli#534]
### Expected Behaviour
After using an Oauth Server-to-Server(oauthSTS) credential during "aio auth login" there should be the ability to utilize "aio console xxx select" commands in order to set the console context for further commands. This is essential for CI/CD pipelines.

### Actual Behaviour
After a successful "aio auth login" with oauthSTS the further commands don't recognize that authentication so "aio console xxx select" still attempts to bounce out to a browser for authentication.

### Reproduce Scenario (including but not limited to)
Basically, create an .aio file with the oauthSTS context. Run "aio auth logout" to ensure no other authentication is currently in the session. Run "aio auth login -c=<context in .aio file>". Run any aio command that would require authentication.

#### Steps to Reproduce
1. Ensure that the application that you can utilize has IO Management API enabled with Oauth Server-to-Server credentials
2. Create an .aio file in the root of where the aio commands will be run from. Example below (copying the credentials from the previous step):
```
{
  "ims": {
    "config": {
      "current": "pipeline"
    },
    "contexts": {
      "pipeline": {
        "client_id": "XXXXXXXXXXX",
        "client_secrets": ["XXXXXXXXXXXXXX"],
        "ims_org_id": "XXXXXXXXXX@AdobeOrg",
        "technical_account_id": "XXXXXXXXXX@techacct.adobe.com",
        "technical_account_email": "XXXXXXXXXXXX@techacct.adobe.com",
        "scopes": [
          "AdobeID",
          "openid",
          "read_organizations",
          "additional_info.projectedProductContext",
          "additional_info.roles",
          "adobeio_api",
          "read_client_secret",
          "manage_client_secrets"
        ],
        "state": ""
      }
    }
  }
}
```
3. Run "aio auth logout" to clear whatever authentication exists
1. Run "aio auth login -c=pipeline". This should return successfully with an access token
1. Run "aio where" to see if an Org/Project/Workspace is selected already (this shouldn't bounce out to a browser...at least it hasn't in my testing)
1. Run "aio console org select" and this bounces out to a browser to authenticate the user and doesn't seem to recognize the oauthSTS authentication.

#### Platform and Version
AIO CLI 9.4.1

#### Logs taken while reproducing problem
Unaware of how to get logs from "aio console org select"

This was originally mentioned https://github.com/adobe/aio-cli-plugin-cloudmanager/issues/676#issuecomment-1764821076 but wanted to bring attention at the root repository so that it gets the correct attention. If this needs to be created under the IMS plugin or the Console plugin then we can track it there as well.

**Comment by edukondaluavula** [comment]
Its worked when changing ims context from pipeline to cli
ex:
{
  "ims": {
    "config": {
      "current": "cli"
    },
    "contexts": {
      "cli": {
        "client_id": "XXXXXXXXXXX",
        "client_secrets": ["XXXXXXXXXXXXXX"],
        "ims_org_id": "XXXXXXXXXX@AdobeOrg",
        "technical_account_id": "XXXXXXXXXX@techacct.adobe.com",
        "technical_account_email": "XXXXXXXXXXXX@techacct.adobe.com",
        "scopes": [
          "AdobeID",
          "openid",
          "read_organizations",
          "additional_info.projectedProductContext",
          "additional_info.roles",
          "adobeio_api",
          "read_client_secret",
          "manage_client_secrets"
        ],
        "state": ""
      }
    }
  }
}

**Comment by martinatime** [comment]
I concur that when switching the context name to "cli" everything works as expected. I don't recall anywhere in the documentation where it stated that the context had to be certain values in order to be looked at especially if you were selecting it as part of the command line arguments. Regardless I will close this issue.
