### ISSUE TITLE
How to log in to aio cli on Linux system

### ISSUE THREAD

**Issue by hbitdeveloper** [adobe/aio-cli#536]
I am currently creating my App Builder App，Follow this operation document：[link](https://developer.adobe.com/app-builder/docs/getting_started/first_app/?query=Signing+in+from+CLI+linux&keywords=&index=all).  When the operation reaches the third step:Signing in from CLI.  **On Windows, enter: aio login.  It was successful to log in**. It will trigger the browser to open and ask me to enter my username and password. After I input, I successfully logged in. **But on Linux systems，It cannot open properly because the Linux system does not have a browser.**  I want to know how to log in to the Linux system.

**Comment by shazron** [comment]
You can't, Adobe IMS requires three-legged OAuth, via the web browser. 

Related: https://github.com/adobe/aio-cli-plugin-auth/issues/54
