### ISSUE TITLE
update activation list format to show additional activation details

### ISSUE THREAD

**Issue by rabbah** [adobe/aio-cli#76]
### Expected Behaviour

This is an enhancement/feature request. When listing activations using `wsk` the activation list is now more richly formatted and shows the activation date/time, status, cold/warm start etc. The `aio` cli output is the older activation list which only contains the activation ids and their corresponding function names.

Sample output from `wsk`:
```
Datetime            Activation ID                    Kind      Start Duration   Status  Entity
2019-10-24 07:38:18 e2f86469271745f3b86469271745f3ec nodejs:10 cold  52ms       success guest/textToSpeech:0.0.4
2019-10-24 06:30:59 8d2e11ea689244cdae11ea689234cd9f nodejs:10 warm  2ms        success guest/hello:0.0.1
```

### Actual Behaviour

```
activations                                   
f652a5f5a7d14e0c92a5f5a7d16e0cf1 imageToText  
76dfe44d904149369fe44d9041d93651 hello 
```

**Comment by shazron** [comment]
I believe this has been implemented in https://github.com/adobe/aio-cli-plugin-runtime/commit/7c11e7ffee955156d0c4637c7eceaf9c63489336#diff-22b60df1df1cb6e7c1cccf8cb357aa61

.. and should be in 1.1.0 of the Runtime plugin. This version of the Runtime plugin should be in the aio-cli `v2.1.0`. Can you verify with `--version` what version you have? Thanks!

**Comment by rabbah** [comment]
Hmm. I see "@adobe/aio-cli": "^2.1.0". I’ll check further.

**Comment by rabbah** [comment]
```
> aio version
@adobe/aio-cli/2.1.1 darwin-x64 node-v10.16.3
```

but i'm not seeing the `--full` flag:
```
> aio runtime:activation:list --help
Lists all the Activations

USAGE
  $ aio runtime:activation:list [ACTIVATIONID]

OPTIONS
  -i, --insecure           bypass certificate check
  -l, --limit=limit        only return LIMIT number of activations from the collection with a maximum LIMIT of 200 activations (default 
                           30)
  -s, --skip=skip          exclude the first SKIP number of activations from the result
  -u, --auth=auth          whisk auth
  -v, --verbose            Verbose output
  --apihost=apihost        whisk API host
  --apiversion=apiversion  whisk API version
  --cert=cert              client cert
  --debug=debug            Debug level output
  --help                   Show help
  --json                   output raw json
  --key=key                client key
  --since=since            return activations with timestamps later than SINCE; measured in milliseconds since Th, 01, Jan 1970
  --upto=upto              return activations with timestamps earlier than UPTO; measured in milliseconds since Th, 01, Jan 1970
  --version                Show version
```

**Comment by rabbah** [comment]
In a separate aio build, I do see `--full` but unable to use it:

```
> aio runtime:activation:list --full
 ›   Error: failed to list the activations: GET https://.../api/v1/namespaces/_/activations?name=--full Returned 
 ›   HTTP 400 (Bad Request) --> "The query parameter 'name' was malformed:
 ›   Parameter may be a 'simple' name or 'package-name/simple' name: --full"
```

**Comment by rabbah** [comment]
@shazron the `--full` flag emits the activation list in `json` and not as a summary table (shown in my first comment). In any case, the correct place for this feature request is the plugin repo and I can open a corresponding issue there.

**Comment by rabbah** [comment]
@shazron you are correct, if I run directly with `aio-cli-plugin-runtime> ./bin/run runtime:activation:list` I am getting the updated table format.
